// packages/web/examples/ssr-with-react-dom/common/App.js
/* eslint-disable react/forbid-prop-types */
import React from 'react';
import PropTypes from 'prop-types';
import { MultiList, ReactiveBase, ReactiveList, SearchBox } from '@appbaseio/reactivesearch';
import BookCard from './BookCard';

// settings for the ReactiveBase component
const settings = {
	app: 'good-books-ds',
	url: 'https://a03a1cb71321:75b6603d-9456-4a5a-af6b-a487b309eb61@appbase-demo-ansible-abxiydt-arc.searchbase.io',
	enableAppbase: true,
};

// props for ReactiveSearch components
// the same props we used server side to generate initial query
const searchBoxProps = {
	dataField: ['original_title', 'original_title.search'],
	componentId: 'BookSensor',
	URLParams: true,
};
const multiListProps = {
	componentId: 'MultiList',
	dataField: 'original_series.keyword',
	size: 100,
	URLParams: true,
	react: {
		and: ['BookSensor'],
	},
};
const reactiveListProps = {
	componentId: 'SearchResult',
	dataField: 'original_title',
	from: 0,
	size: 10,
	renderItem: data => <BookCard key={data._id} data={data} />,
	react: {
		and: ['BookSensor', 'MultiList'],
	},
	URLParams: true,
	pagination: true,
};
const App = ({ store, contextCollector }) => (
	<ReactiveBase
		{...settings}
		initialState={store}
		{...(contextCollector ? { contextCollector } : {})}
	>
		<div className="row">
			<div className="col">
				<SearchBox {...searchBoxProps} />
				<MultiList {...multiListProps} />
			</div>

			<div className="col">
				<ReactiveList {...reactiveListProps} />
			</div>
		</div>
	</ReactiveBase>
);

App.propTypes = {
	settings: PropTypes.object,
	store: PropTypes.object,
	contextCollector: PropTypes.func,
};

export default App;

// packages/vue/examples/search-showcase/auto-suggestions/src/App.vue
<template>
	<div id="app">
		<reactive-base
			app="good-books-ds"
			url="https://a03a1cb71321:75b6603d-9456-4a5a-af6b-a487b309eb61@appbase-demo-ansible-abxiydt-arc.searchbase.io"
		>
			<search-box
				className="result-list-container"
				componentId="BookSensor"
				:dataField="['original_title', 'original_title.search']"
				:URLParams="true"
				:size="10"
				:autosuggest="true"
			/>
			<reactive-list
				componentId="SearchResult"
				dataField="original_title.keyword"
				className="result-list-container"
				:pagination="true"
				:size="5"
				:react="{ and: ['BookSensor'] }"
			>
				<template #renderItem="{ item }">
					<div :id="item._id" class="flex book-content" :key="item._id">
						<img :src="item.image" alt="Book Cover" class="book-image" />
						<div class="flex column justify-center ml20">
							<div class="book-header">{{ item.original_title }}</div>
							<div class="flex column justify-space-between">
								<div>
									<div>
										by <span class="authors-list">{{ item.authors }}</span>
									</div>
									<div class="ratings-list flex align-center">
										<span class="stars">
											<i
												v-for="(item, index) in Array(
													item.average_rating_rounded,
												).fill('x')"
												class="fas fa-star"
												:key="index"
											/>
										</span>
										<span class="avg-rating"
											>({{ item.average_rating }} avg)</span
										>
									</div>
								</div>
								<span class="pub-year"
									>Pub {{ item.original_publication_year }}</span
								>
							</div>
						</div>
					</div>
				</template>
			</reactive-list>
		</reactive-base>
	</div>
</template>

<script>
import './styles.css';
import { ReactiveBase, ReactiveList, SearchBox } from '@appbaseio/reactivesearch-vue';

export default {
	name: 'app',
	components: { ReactiveBase, ReactiveList, SearchBox },
};
</script>

<style>
#app {
	font-family: 'Avenir', Helvetica, Arial, sans-serif;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	color: #2c3e50;
}
</style>
